### PR TITLE
zip file with a deflated directory can't be written out again

### PR DESCRIPTION
**Pull request by ntyni**
JAR files created with OpenJDK contain a deflated META-INF directory. Such a zip file can be read with Archive::Zip but can't be written out again. Writing fails with

      subclass Responsibility
        at blib/lib/Archive/Zip/Archive.pm line 420.

This broke with 1.40, specifically the fix for [rt.cpan.org #92205].

The first commit here adds a TODO test for this. The second commit seems to fix it, but I haven't really researched why. It partly reverts the change in 1.40 but doesn't seem to break the tests added there.

Please note that this is related to [rt.cpan.org #73797], which has outdated patches and can be closed. The issue was fixed in a different way for some time between 1.30 and 1.40, but handling JAR files then broke again as no regression tests were ever added.

Many thanks for your work on Archive-Zip!

### CODE REVIEW

**Comment by ntyni** [comment]
Whoops, I only noticed now that this is also issue #13. Sorry about the duplicate!

**Comment by redhotpenguin** [comment]
Is this still an issue? Happy to apply your fix still.

**Comment by ntyni** [comment]
Yes, I believe it still applies.

**Comment by ntyni** [comment]
I see rebasing and fixing my old patches accidentally left a 2012 date to the first commit. Not sure how to fix that cleanly, apologies for any confusion.

**Pull request merged**
