### PR TITLE
Add github workflows to get Linux/Windows & macOS

### PR DESCRIPTION
**Pull request by pmqs**
This change gives us more up front testing, including macOS for the first time.

### CODE REVIEW

**Comment by redhotpenguin** [comment]
One test failure, but LGTM

**Comment by pmqs** [comment]
> One test failure, but LGTM

Already highlighted the failure to  @farblos. Appears to be a race condition in one of the tests.

**Comment by redhotpenguin** [comment]
LMK if you want me to merge or wait for an update.

**Comment by pmqs** [comment]
Think we should merge. Will give us more coverage for our tests

**Comment by farblos** [comment]
> Think we should merge. Will give us more coverage for our tests

I agree, but one question:

I'm not familiar with github workflows, so I'm not sure whether these new tests would run with one of the environment variables triggering additional test output (from `common.pm`):

```
use constant _IN_AUTOTEST_ENVIRONMENT =>
    exists($ENV{'AUTOMATED_TESTING'}) ||
    exists($ENV{'NONINTERACTIVE_TESTING'}) ||
    exists($ENV{'PERL_CPAN_REPORTER_CONFIG'});
```

If none of these variables is set, could we get one with some additional statements or what not? For `.appveyor.yml`, for example, I have added an explicit `set AUTOMATED_TESTING=1`. For `.travis.yml` one of the variables was already set out of the box, don't remember which and how.

**Comment by farblos** [comment]
Just drilled down the workflow test results to confirm that the test results are not as verbose as they could be (checked for Windows and MacOS). @pmqs could you please set `AUTOMATED_TESTING` before making `test`?

Thanks!

**Comment by pmqs** [comment]
> @pmqs could you please set `AUTOMATED_TESTING` before making `test`?


Done

**Pull request merged**
