### PR TITLE
Fix for members using bzip compression

### PR DESCRIPTION
**Pull request by pmqs**
This PR addresses https://github.com/redhotpenguin/perl-Archive-Zip/issues/26

### CODE REVIEW

**Comment by pmqs** [comment]
All CI tests passed, apart from 5.14.

That one failed because Test/MockModule.pm wasn't available.

**Comment by AGWA** [comment]
For the record, I release the bzip.zip test archive in this pull request under the same licensing terms as Archive::Zip.

**Comment by lamby** [comment]
Apart from not quiite matching the existing code style, LGTM :)

**Comment by redhotpenguin** [comment]
Merging this based on @lamby's LGTM

**Pull request merged**
